//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutMe
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Birth { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Photo { get; set; }
        public string CV { get; set; }
        public string Position { get; set; }
        public string Text { get; set; }
        public string Lang { get; set; }
    }
}
